import type { Metadata } from "next";
import Noto_Sans_JP from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const fontNotoSansJP = Noto_Sans_JP({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "BLOG APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(
          "bg-background text-foreground antialiased min-h-screen",
          fontNotoSansJP.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
