import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "BLOG APP",
  description: "Generated by create next app",
  url: "https://blog-app.vercel.app",
  ogImage: "",
  links: {
    x: "https://twitter.com",
    github: "https://github.com",
  },
};
